### PR TITLE
feat: email service

### PR DESCRIPTION
**Pull request by jyecusch**

### CODE REVIEW

**Review by tjholm — APPROVED** [review]
LGTM

**Comment by davemooreuws** [comment]
Do we want to add the ability to view statistics? Example: GetSendStatistics in SES

**Review by davemooreuws — APPROVED** [review]

**Comment by medgar-nitric** [comment]
Should give some thought to supporting file attachments.

**Review by medgar-nitric — APPROVED** [review]
Looks good. I would recommend thinking about how you would support file attachments as well.

**Comment by jyecusch** [comment]
> Looks good. I would recommend thinking about how you would support file attachments as well.

Agreed, I looked at how AWS and Google handle attachments and they're both separate API methods from the basic email with content style messages. So we can add that as an enhancement too as it's needed.

**Pull request merged**
